name: Pull Requests

on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 14 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Set executable flag on gradlew
        run: chmod +x gradlew
      - name: Execute tests
        env:
          GH_PACKAGES_READ_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew test