name: Publish

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract release version
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Set executable flag on gradlew
        run: chmod +x gradlew
      - name: Execute tests and build executable fatJar
        run: ./gradlew test shadowJar -PreleaseVersion=$RELEASE_VERSION
      - name: Upload file to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/manami.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}