name: Publish

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract release version
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Set executable flag on gradlew
        run: chmod +x gradlew
      - name: Execute tests
        env:
          GITHUB_PACKAGES_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: ./gradlew test -Prelease.version=$RELEASE_VERSION -Pgpr.key=$GITHUB_PACKAGES_ACCESS_TOKEN
      - name: Set version
        run: echo $RELEASE_VERSION > manami-app/src/main/resources/manami.version
      - name: Build executable fatJar
        env:
          GITHUB_PACKAGES_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: ./gradlew shadowJar -Prelease.version=$RELEASE_VERSION -Pgpr.key=$GITHUB_PACKAGES_ACCESS_TOKEN
      - name: Upload file to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/manami.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}