name: Pull Requests

on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
      - '.github/workflows/**'
      - '!.github/workflows/pull-requests.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21, x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Set executable flag on gradlew
        run: chmod +x gradlew
      - name: Execute tests
        env:
          GH_PACKAGES_READ_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN }}
        run: ./gradlew test
      - name: Generate coverage
        if: ${{ matrix.java == 21 }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew manami-app:jacocoTestReport manami-app:coverallsJacoco