name: Gradle Wrapper Update

on:
  schedule:
    - cron: "0 20 * * 1"

jobs:
  update:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: update gradle
        id: gradleUpdate
        uses: EdwarDDay/upgrade-gradle-action@v1
        with:
          distribution-type: "bin"

      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update gradle to ${{ steps.gradleUpdate.outputs.gradle-version }}"
          branch: "gradle_update/version_${{ steps.gradleUpdate.outputs.gradle-version }}"
          delete-branch: true
          title: "Update gradle to ${{ steps.gradleUpdate.outputs.gradle-version }}"
          body: |
            ${{ steps.gradleUpdate.outputs.version-information }}

            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          labels: "dependencies,gradle"
